<?xml version="1.0" encoding="UTF-8"?>
<project name="mkv-scanner" basedir="." default="create-jar.runtime"
         xmlns:unless="ant:unless"
         xmlns:ivy="antlib:org.apache.ivy.ant">

    <property name="ivy.install.version"       value="2.4.0"/>
    <property name="ivy.jar.dir"               value="${basedir}/ivy"/>
    <property name="ivy.jar.file"              value="${ivy.jar.dir}/ivy.jar"/>
    <property name="src.main.dir"              value="src/main/java"/>
    <property name="src.test.dir"              value="src/test/java"/>
    <property name="resources.main.dir"        value="src/main/resources"/>
    <property name="lib.dir"                   value="lib"/>
    <property name="build.dir"                 value="build"/>
    <property name="build.main.dir"            value="${build.dir}/main"/>
    <property name="build.test.dir"            value="${build.dir}/test"/>
    <property name="target.dir"                value="target"/>
    <property name="report.dir"                value="${build.test.dir}/report"/>
    <property name="dist.dir"                  value="dist"/>
    <property name="javadoc.dir"               value="javadoc"/>
    <property name="artifact.name"             value="mkvscanner"/>

    <path id="classpath.ivy-runtime">
        <fileset dir="${lib.dir}/runtime">
            <include name="**/*.jar"/>
        </fileset>
    </path>
    <path id="classpath.ivy-test">
        <fileset dir="${lib.dir}/test">
            <include name="**/*.jar"/>
        </fileset>
    </path>
    <path id="classpath.test">
        <fileset dir="${lib.dir}/test">
            <include name="**/*.jar"/>
        </fileset>
        <pathelement path="${build.main.dir}"/>
        <pathelement path="${build.test.dir}"/>
        <!-- so Eac3toScanner can load /eac3to-languages.txt and /eac3to-format-extensions.json at test time -->
        <pathelement location="${resources.main.dir}"/>
    </path>

    <available file="${ivy.jar.file}" property="ivy.installed"/>
    <available file="${ant.home}/lib/junit-jupiter-api.jar" property="junit.installed"/>

    <target name="ivy.load-settings" depends="ivy.install">
        <ivy:settings file="ivySettings.xml"/>
    </target>

    <target name="ivy.download" unless="ivy.installed" description="downloads the ivy jar file">
        <echo message="downloading ivy..."/>
        <mkdir dir="${ivy.jar.dir}"/>
        <get src="https://repo1.maven.org/maven2/org/apache/ivy/ivy/${ivy.install.version}/ivy-${ivy.install.version}.jar" dest="${ivy.jar.file}" usetimestamp="true"/>
    </target>

    <target name="ivy.install" depends="ivy.download" description="registers the ivy antlib in ant">
        <echo message="registering ivy antlib..."/>
        <path id="ivy.lib.path">
            <fileset dir="${ivy.jar.dir}" includes="*.jar"/>
        </path>
        <taskdef resource="org/apache/ivy/ant/antlib.xml" uri="antlib:org.apache.ivy.ant" classpathref="ivy.lib.path"/>
    </target>

    <target name="ivy.resolve.main" depends="ivy.install, ivy.load-settings" description="resolve ivy dependencies for running the server">
        <ivy:retrieve conf="runtime" pattern="${lib.dir}/[conf]/[organisation]-[artifact]-[revision].[ext]"/>
    </target>

    <target name="ivy.resolve.test" depends="ivy.install" description="resolve ivy dependencies for tests">
        <ivy:retrieve pattern="${lib.dir}/[conf]/[organisation]-[artifact]-[revision].[ext]" conf="test"/>
    </target>

    <target name="junit.install" depends="ivy.resolve.test" unless="junit.installed" description="installs junit libs into ANT_HOME">
<!--        <echo message="installing ant junit libs to ${ant.home}; IF THIS FAILS, YOU MUST FIRST RUN 'sudo ant junit.install'"/>-->
<!--        <copy file="lib/test/org.junit.jupiter-junit-jupiter-api-5.4.2.jar" tofile="${ant.home}/lib/junit-jupiter-api.jar"/>-->
<!--        <copy file="lib/test/org.junit.jupiter-junit-jupiter-engine-5.4.2.jar" tofile="${ant.home}/lib/junit-jupiter-engine.jar"/>-->
<!--        <copy file="lib/test/org.junit.platform-junit-platform-commons-1.4.2.jar" tofile="${ant.home}/lib/junit-platform-commons.jar"/>-->
<!--        <copy file="lib/test/org.junit.platform-junit-platform-engine-1.4.2.jar" tofile="${ant.home}/lib/junit-platform-engine.jar"/>-->
<!--        <copy file="lib/test/org.junit.platform-junit-platform-launcher-1.4.2.jar" tofile="${ant.home}/lib/junit-platform-launcher.jar"/>-->
<!--        <copy file="lib/test/org.opentest4j-opentest4j-1.1.1.jar" tofile="${ant.home}/lib/opentest4j.jar"/>-->
    </target>

    <target name="compile.main" depends="ivy.resolve.main" description="compile source">
        <mkdir dir="${build.main.dir}"/>
        <javac destdir="${build.main.dir}" includeantruntime="false" classpathref="classpath.ivy-runtime">
            <src path="${src.main.dir}"/>
        </javac>
    </target>

    <target name="compile.test" depends="compile.main, ivy.resolve.test" description="compiles the tests">
        <mkdir dir="${build.test.dir}"/>
        <javac destdir="${build.test.dir}" includeantruntime="false">
            <classpath>
                <pathelement path="${build.main.dir}"/>
                <fileset dir="${lib.dir}/test" includes="*.jar"/>
            </classpath>
            <src path="${src.test.dir}"/>
        </javac>
    </target>

    <target name="copy.resources" description="copy resources to build dir">
        <copy todir="${build.main.dir}">
            <fileset dir="${resources.main.dir}"/>
        </copy>
    </target>

    <target name="create-jar.runtime" depends="compile.main, copy.resources" description="creates a jar file in the target directory">
        <mkdir dir="${target.dir}"/>
        <jar destfile="${target.dir}/${artifact.name}.jar" basedir="${build.main.dir}"/>
    </target>

    <target name="create-jar.sources" depends="ivy.resolve.main">
        <jar destfile="${dist.dir}/${artifact.name}-${ivy.revision}-sources.jar">
            <fileset dir="${src.main.dir}" includes="**/*.java"/>
            <fileset dir="${resources.main.dir}" includes="**/*"/>
        </jar>
    </target>

    <target name="create-jar.javadoc" depends="ivy.resolve.main">
        <javadoc sourcepath="${src.main.dir}" destdir="${javadoc.dir}" classpathref="classpath.ivy-runtime"/>
        <jar basedir="${javadoc.dir}" file="${dist.dir}/${artifact.name}-${ivy.revision}-javadoc.jar"/>
    </target>

    <target name="test" depends="compile.test, junit.install" description="Runs all of the tests. Use test.name (FQ class name) and optionally test.functions (comma-separated list) to run specific tests">
        <delete dir="${report.dir}" failonerror="false"/>
        <mkdir dir="${report.dir}"/>
        <junitlauncher failureproperty="test-failed">
            <classpath refid="classpath.test"/>
            <testclasses unless:set="test.name" outputdir="${report.dir}">
                <fileset dir="${build.test.dir}">
                    <include name="**/*" />
                </fileset>
                <listener type="legacy-xml" sendSysOut="true" sendSysErr="true"/>
                <listener type="legacy-plain" sendSysOut="true" sendSysErr="true"/>
            </testclasses>
        </junitlauncher>
        <condition property="test-one-class.test-some">
            <and>
                <isset property="test.name"/>
                <isset property="test.functions"/>
            </and>
        </condition>
        <condition property="test-one-class.test-all">
            <and>
                <isset property="test.name"/>
                <not><isset property="test.functions"/></not>
            </and>
        </condition>
        <antcall target="-test.test-one-class.test-all-functions"/>
        <antcall target="-test.test-one-class.test-some-functions"/>
        <junitreport todir="${report.dir}">
            <fileset dir="${report.dir}" includes="TEST-*.xml"/>
            <report todir="${report.dir}"/>
        </junitreport>
        <concat fixlastline="true">
            <fileset dir="${report.dir}" includes="*.txt"/>
        </concat>
        <fail if="test-failed" message="ONE OR MORE TESTS FAILED."/>
    </target>

    <target name="-test.test-one-class.test-all-functions" if="test-one-class.test-all">
        <echo message="Testing `${test.name}`, all tests"/>
        <junitlauncher failureproperty="test-failed">
            <classpath refid="classpath.test"/>
            <test outputdir="${report.dir}" name="${test.name}">
                <listener type="legacy-xml" sendSysOut="true" sendSysErr="true"/>
                <listener type="legacy-plain" sendSysOut="true" sendSysErr="true"/>
            </test>
        </junitlauncher>
        <junitreport todir="${report.dir}">
            <fileset dir="${report.dir}" includes="TEST-*.xml"/>
            <report todir="${report.dir}"/>
        </junitreport>
        <concat fixlastline="true">
            <fileset dir="${report.dir}" includes="*.txt"/>
        </concat>
        <fail if="test-failed" message="ONE OR MORE TESTS FAILED."/>
    </target>

    <target name="-test.test-one-class.test-some-functions" if="test-one-class.test-some">
        <echo message="Testing `${test.name}#${test.functions}`"/>
        <junitlauncher failureproperty="test-failed">
            <classpath refid="classpath.test"/>
            <test outputdir="${report.dir}" name="${test.name}" methods="${test.functions}">
                <listener type="legacy-xml" sendSysOut="true" sendSysErr="true"/>
                <listener type="legacy-plain" sendSysOut="true" sendSysErr="true"/>
            </test>
        </junitlauncher>
        <junitreport todir="${report.dir}">
            <fileset dir="${report.dir}" includes="TEST-*.xml"/>
            <report todir="${report.dir}"/>
        </junitreport>
        <concat fixlastline="true">
            <fileset dir="${report.dir}" includes="*.txt"/>
        </concat>
        <fail if="test-failed" message="ONE OR MORE TESTS FAILED."/>
    </target>


    <target name="publish" depends="ivy.resolve.main, publish.validate, create-jar.sources, create-jar.runtime, create-jar.javadoc" description="publishes artifact to an ivy/maven-compliant repository. Required parameters: publish.resolver, key.password, (and for non-local publishing) publish.user, publish.password">
        <copy file="${target.dir}/${artifact.name}.jar" tofile="${dist.dir}/${artifact.name}-${ivy.revision}.jar"/>
        <ivy:makepom ivyfile="ivy.xml" templatefile="pomTemplate.xml" pomfile="${dist.dir}/${artifact.name}-${ivy.revision}.pom"/>
        <sign-file file="${dist.dir}/${artifact.name}-${ivy.revision}.jar"/>
        <sign-file file="${dist.dir}/${artifact.name}-${ivy.revision}-sources.jar"/>
        <sign-file file="${dist.dir}/${artifact.name}-${ivy.revision}-javadoc.jar"/>
        <sign-file file="${dist.dir}/${artifact.name}-${ivy.revision}.pom"/>
        <ivy:publish status="${publish.status}" resolver="${publish.resolver}" overwrite="true"
                     artifactspattern="${dist.dir}/[artifact]-[revision](-[classifier]).[ext]" publishivy="false"/>
    </target>

    <macrodef name="sign-file">
        <attribute name="file"/>
        <sequential>
            <exec executable="sh">
                <arg value="-c"/>
                <arg value="gpg2 -a -b --yes --pinentry-mode loopback --passphrase &quot;${key.password}&quot; @{file}"/>
            </exec>
        </sequential>
    </macrodef>

    <target name="publish.validate">
        <!-- default the optional params to empty so the checks below treat "unset" and "set but blank" alike -->
        <property name="publish.resolver" value=""/>
        <property name="publish.user"     value=""/>
        <property name="publish.password" value=""/>
        <property name="key.password"     value=""/>

        <fail message="parameter key.password is required for gpg to sign artifacts">
            <condition><equals arg1="${key.password}" arg2=""/></condition>
        </fail>

        <condition property="publish.to-nexus">
            <or>
                <equals arg1="${publish.resolver}" arg2="nexus-staging"/>
                <equals arg1="${publish.resolver}" arg2="nexus-snapshots"/>
            </or>
        </condition>
        <fail message="parameter publish.user required when publishing to ${publish.resolver}">
            <condition>
                <and>
                    <isset property="publish.to-nexus"/>
                    <equals arg1="${publish.user}" arg2=""/>
                </and>
            </condition>
        </fail>
        <fail message="parameter publish.password required when publishing to ${publish.resolver}">
            <condition>
                <and>
                    <isset property="publish.to-nexus"/>
                    <equals arg1="${publish.password}" arg2=""/>
                </and>
            </condition>
        </fail>

        <condition property="publish.is-snapshot">
            <matches string="${ivy.revision}" pattern="snapshot$" casesensitive="false"/>
        </condition>
        <fail message="parameter publish.resolver must be &quot;nexus-snapshots&quot; or &quot;local&quot; for a snapshot version: ${ivy.revision}">
            <condition>
                <and>
                    <isset property="publish.is-snapshot"/>
                    <not>
                        <or>
                            <equals arg1="${publish.resolver}" arg2="nexus-snapshots"/>
                            <equals arg1="${publish.resolver}" arg2="local"/>
                        </or>
                    </not>
                </and>
            </condition>
        </fail>
        <fail message="parameter publish.resolver must be &quot;nexus-staging&quot; or &quot;local&quot; for a non-snapshot version: ${ivy.revision}">
            <condition>
                <and>
                    <not><isset property="publish.is-snapshot"/></not>
                    <not>
                        <or>
                            <equals arg1="${publish.resolver}" arg2="nexus-staging"/>
                            <equals arg1="${publish.resolver}" arg2="local"/>
                        </or>
                    </not>
                </and>
            </condition>
        </fail>

        <condition property="publish.status" value="snapshot">
            <isset property="publish.is-snapshot"/>
        </condition>
        <property name="publish.status" value="release"/>
    </target>

    <target name="clean" description="cleans all build artifacts">
        <delete includeemptydirs="true" quiet="true">
            <fileset dir="${lib.dir}"/>
            <fileset dir="${build.dir}"/>
            <fileset dir="${target.dir}"/>
            <fileset dir="${dist.dir}"/>
            <fileset dir="${javadoc.dir}"/>
        </delete>
    </target>

    <target name="clean.ant-deps" description="clean the ivy installation">
        <delete dir="${ivy.jar.dir}"/>
    </target>

    <target name="ivy.clean-cache" depends="ivy.install" description="clean the ivy cache">
        <ivy:cleancache/>
    </target>
</project>
